### ISSUE TITLE
Publish on packagist?

### ISSUE THREAD

**Issue by kumy** [geofmureithi/f3-validate#3]
I cannot find this package on https://packagist.org, may you publish it there? That would help for installing, maintaining it up to date, and we don't have to commit external packages in our vcs.

Thanks

**Comment by geofmureithi** [comment]
Hey yea..
This is the plan.

- Do some refactoring.
- Setup Tests
- Publish for composer
- Setup for travis.

**Comment by geofmureithi** [comment]
Fixed:
https://github.com/geofmureithi/f3-validate/releases/tag/1.1
